---
Gemfile:
  optional:
    ':test':
      - gem: 'beaker'
      - gem: 'beaker-rspec'
      - gem: 'beaker-hostgenerator'
      - gem: 'beaker-puppet'
      - gem: 'beaker-puppet_install_helper'

.travis.yml:
  extras:
  -
    env: CHECK=beaker PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=centos7-64{hypervisor=docker}
    services: docker
    sudo: required
